analytics: {}
color:
  brandColors:
    - '#000000'
    - '#2078B8'
    - '#88A850'
    - '#80B028'
    - '#000000'
  brandStrength: 0.307482
  lightness: 0.144943
  rhythmicContrast: 0.061819
  saturation: 0.521895
cta: {}
layout_spectrum: 1
name: Integrated Rehab
opengraph: {}
purpose: {}
typography_spectrum: 0.42652
