analytics: {}
color:
  brandColors:
    - '#D0E0D0'
    - '#80A828'
    - '#708050'
    - '#90C040'
    - '#98C0E8'
  brandStrength: 0.513513
  lightness: 0.144943
  rhythmicContrast: 0.321791
  saturation: 0.521895
cta: {}
layout_spectrum: 1
name: Integrated Rehab
opengraph: {}
purpose: {}
typography_spectrum: 0.42652
